import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SnapCase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={recursive.className}>
        <main className="flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]">
          <Navbar />
          <div className="flex flex-1 flex-col h-full">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
